- name: Create service target
  template: src=target.j2 dest=/etc/systemd/system/{{ service_name }}.target mode=644
  register: target_file

- name: Enable target
  service: name={{ service_name }}.target enabled={{ service_enabled }}

- name: Create service units
  template: src=unit.j2 dest=/etc/systemd/system/{{ item.name }}{% if item.instances|default(False) %}@{% endif %}.service mode=644
  register: unit_files
  with_items: "{{ service_units }}"

- name: Enable and start unit service instances
  service: name={{ item.0.name }}@{{ item.1 }} state={{ 'started' if service_enabled else 'stopped'}} enabled={{ service_enabled }}
  with_subelements:
    - "{{ service_units }}"
    - instances
    - { skip_missing: True }
  notify: reload services

- name: Enable and start single units
  service: name={{ item.name }}  state={{ 'stopped' if service_enabled else 'stopped'}} enabled={{ service_enabled }}
  with_items:
    - "{{ service_units }}"
  when: item.instances is not defined
  notify: reload services
